-- Generated by scripts/generate-patient-profile-seed.mjs.
-- Edit the validated JSON sources, then run yarn seed:generate.

begin;

insert into public.patient_profiles (
  id, scope, slug, status, created_at, updated_at
) values (
  '0716cbfe-b94e-47fe-8cdf-a189fd965c6e', 'system', 'adam-marsden', 'active', '2026-08-30T00:00:00.000Z', '2026-08-30T00:00:00.000Z'
) on conflict (slug) where scope = 'system' do nothing;

do $verify_profile_adam_marsden$
begin
  if not exists (
    select 1 from public.patient_profiles
    where scope = 'system'
      and slug = 'adam-marsden'
      and organisation_id is null
      and user_id is null
  ) then
    raise exception 'production_patient_profile_drift:adam-marsden';
  end if;
end;
$verify_profile_adam_marsden$;

with content as (
  select $patient_document_adam_marsden$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Adam"
    ],
    "familyName": "Marsden",
    "dateOfBirth": "2003-03-14",
    "sexAtBirth": {
      "status": "known",
      "value": "male"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-71304",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "known",
      "value": {
        "display": "White British"
      }
    },
    "faithOrBelief": {
      "status": "unknown"
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [],
    "accessibilityNeeds": []
  },
  "contact": {
    "address": {
      "lines": [
        "14 Meredith Street"
      ],
      "city": "Manchester",
      "postalCode": "M12 6BE",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "sandra-marsden",
      "name": "Sandra Marsden",
      "relationship": {
        "display": "Mother"
      },
      "roles": [
        "next_of_kin"
      ],
      "notes": "Lives with Adam and his younger siblings."
    }
  ],
  "background": [
    {
      "id": "family-home",
      "category": "living_arrangements",
      "summary": "Lives with his mother and younger siblings in Ardwick.",
      "sensitivity": "standard"
    },
    {
      "id": "limited-social-network",
      "category": "social",
      "summary": "Has no wider social network and is experiencing financial difficulties.",
      "sensitivity": "standard"
    },
    {
      "id": "childhood-adversity",
      "category": "adverse_life_event",
      "summary": "Experienced domestic violence, physical abuse and paternal alcohol dependence during childhood.",
      "details": "His father died when Adam was 15. His later history includes school exclusion and early contact with the criminal justice system.",
      "sensitivity": "restricted"
    },
    {
      "id": "exploitation-risk",
      "category": "safeguarding",
      "summary": "Cannabis-related debts may create vulnerability to exploitation.",
      "sensitivity": "restricted"
    }
  ],
  "problems": [
    {
      "id": "schizophrenia",
      "problem": {
        "display": "Schizophrenia"
      },
      "clinicalStatus": "active",
      "details": "A recent diagnosis in the source material."
    }
  ],
  "allergies": [],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "A young adult with recently diagnosed schizophrenia, limited social support and a history requiring trauma-informed and safeguarding-aware care.",
    "lifeStage": "young_person",
    "careSettings": [
      "community_mental_health",
      "home"
    ],
    "specialties": [
      "mental_health"
    ],
    "tags": [
      "mental_health",
      "safeguarding"
    ]
  }
}
$patient_document_adam_marsden$::jsonb as document
), profile as (
  select id
  from public.patient_profiles
  where scope = 'system'
    and slug = 'adam-marsden'
)
insert into public.patient_profile_versions (
  id,
  patient_profile_id,
  version_number,
  state,
  schema_version,
  document,
  content_hash,
  change_summary,
  source_reference,
  source_revision,
  created_at,
  updated_at
)
select
  '14ed71d9-685a-4996-a60f-f02a5bf0586b',
  profile.id,
  1,
  'draft',
  1,
  document,
  encode(sha256(convert_to(document::text, 'UTF8')), 'hex'),
  'Initial clinically informed import from the EPR Unified prototype; review required before publication.',
  'https://github.com/DNMSW/epr-unified',
  '03c7f12',
  '2026-08-30T00:00:00.000Z',
  '2026-08-30T00:00:00.000Z'
from content
cross join profile
on conflict (patient_profile_id, version_number) do nothing;

do $verify_version_adam_marsden$
declare
  expected_hash text;
  stored_hash text;
  stored_document_hash text;
begin
  select encode(
    sha256(convert_to($patient_document_adam_marsden$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Adam"
    ],
    "familyName": "Marsden",
    "dateOfBirth": "2003-03-14",
    "sexAtBirth": {
      "status": "known",
      "value": "male"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-71304",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "known",
      "value": {
        "display": "White British"
      }
    },
    "faithOrBelief": {
      "status": "unknown"
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [],
    "accessibilityNeeds": []
  },
  "contact": {
    "address": {
      "lines": [
        "14 Meredith Street"
      ],
      "city": "Manchester",
      "postalCode": "M12 6BE",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "sandra-marsden",
      "name": "Sandra Marsden",
      "relationship": {
        "display": "Mother"
      },
      "roles": [
        "next_of_kin"
      ],
      "notes": "Lives with Adam and his younger siblings."
    }
  ],
  "background": [
    {
      "id": "family-home",
      "category": "living_arrangements",
      "summary": "Lives with his mother and younger siblings in Ardwick.",
      "sensitivity": "standard"
    },
    {
      "id": "limited-social-network",
      "category": "social",
      "summary": "Has no wider social network and is experiencing financial difficulties.",
      "sensitivity": "standard"
    },
    {
      "id": "childhood-adversity",
      "category": "adverse_life_event",
      "summary": "Experienced domestic violence, physical abuse and paternal alcohol dependence during childhood.",
      "details": "His father died when Adam was 15. His later history includes school exclusion and early contact with the criminal justice system.",
      "sensitivity": "restricted"
    },
    {
      "id": "exploitation-risk",
      "category": "safeguarding",
      "summary": "Cannabis-related debts may create vulnerability to exploitation.",
      "sensitivity": "restricted"
    }
  ],
  "problems": [
    {
      "id": "schizophrenia",
      "problem": {
        "display": "Schizophrenia"
      },
      "clinicalStatus": "active",
      "details": "A recent diagnosis in the source material."
    }
  ],
  "allergies": [],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "A young adult with recently diagnosed schizophrenia, limited social support and a history requiring trauma-informed and safeguarding-aware care.",
    "lifeStage": "young_person",
    "careSettings": [
      "community_mental_health",
      "home"
    ],
    "specialties": [
      "mental_health"
    ],
    "tags": [
      "mental_health",
      "safeguarding"
    ]
  }
}
$patient_document_adam_marsden$::jsonb::text, 'UTF8')),
    'hex'
  ) into expected_hash;

  select
    content_hash,
    encode(sha256(convert_to(document::text, 'UTF8')), 'hex')
  into stored_hash, stored_document_hash
  from public.patient_profile_versions version
  join public.patient_profiles profile
    on profile.id = version.patient_profile_id
  where profile.scope = 'system'
    and profile.slug = 'adam-marsden'
    and version_number = 1
    and version.state = 'draft'
    and version.schema_version = 1;

  if stored_hash is null or
     stored_hash <> expected_hash or
     stored_document_hash <> expected_hash then
    raise exception 'production_patient_profile_version_drift:adam-marsden';
  end if;
end;
$verify_version_adam_marsden$;

insert into public.patient_profiles (
  id, scope, slug, status, created_at, updated_at
) values (
  '45d1b136-8a97-4628-873a-57971e411bad', 'system', 'adebayo-omolade', 'active', '2026-08-30T00:00:00.000Z', '2026-08-30T00:00:00.000Z'
) on conflict (slug) where scope = 'system' do nothing;

do $verify_profile_adebayo_omolade$
begin
  if not exists (
    select 1 from public.patient_profiles
    where scope = 'system'
      and slug = 'adebayo-omolade'
      and organisation_id is null
      and user_id is null
  ) then
    raise exception 'production_patient_profile_drift:adebayo-omolade';
  end if;
end;
$verify_profile_adebayo_omolade$;

with content as (
  select $patient_document_adebayo_omolade$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Adebayo"
    ],
    "familyName": "Omolade",
    "dateOfBirth": "2006-03-15",
    "sexAtBirth": {
      "status": "known",
      "value": "male"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-63820",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "known",
      "value": {
        "display": "Black British, with family roots in Nigeria"
      }
    },
    "faithOrBelief": {
      "status": "known",
      "value": {
        "display": "Christian"
      }
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "proficiency": "fluent",
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [
      {
        "id": "plain-language",
        "summary": "Use plain language and avoid unexplained medical terminology.",
        "details": "Allow time to process information and check understanding without rushing."
      }
    ],
    "accessibilityNeeds": [
      {
        "id": "learning-disability-support",
        "summary": "Requires reasonable adjustments for a mild to moderate learning disability.",
        "details": "May become anxious or overwhelmed by complex written information and has a learning disability healthcare passport."
      }
    ]
  },
  "contact": {
    "address": {
      "lines": [
        "14 Ashton View"
      ],
      "city": "Tameside",
      "postalCode": "AS1 4NN",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "folake-omolade",
      "name": "Folake Omolade",
      "relationship": {
        "display": "Sister"
      },
      "roles": [
        "next_of_kin",
        "carer"
      ],
      "notes": "Main source of emotional and practical support, including help with appointments, forms and written information."
    }
  ],
  "background": [
    {
      "id": "living-with-sister",
      "category": "living_arrangements",
      "summary": "Lives with his older sister Folake.",
      "sensitivity": "standard"
    },
    {
      "id": "charity-shop-work",
      "category": "occupation",
      "summary": "Works part-time in a charity shop with support and values the structure and independence.",
      "sensitivity": "standard"
    },
    {
      "id": "prayer-when-worried",
      "category": "cultural",
      "summary": "Finds quiet prayer comforting when worried and prefers this to be approached sensitively.",
      "sensitivity": "standard"
    }
  ],
  "problems": [
    {
      "id": "type-2-diabetes",
      "problem": {
        "display": "Type 2 diabetes mellitus"
      },
      "clinicalStatus": "active",
      "details": "Diagnosed five months before the source scenario."
    },
    {
      "id": "learning-disability",
      "problem": {
        "display": "Learning disability"
      },
      "clinicalStatus": "active",
      "details": "Described as mild to moderate in the source material."
    }
  ],
  "allergies": [],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "A young adult with type 2 diabetes and a learning disability who values independence and benefits from accessible communication.",
    "lifeStage": "young_person",
    "careSettings": [
      "primary_care",
      "community"
    ],
    "specialties": [
      "diabetes",
      "learning_disability"
    ],
    "tags": [
      "accessibility",
      "carer_relationship",
      "cultural_context",
      "long_term_condition"
    ]
  }
}
$patient_document_adebayo_omolade$::jsonb as document
), profile as (
  select id
  from public.patient_profiles
  where scope = 'system'
    and slug = 'adebayo-omolade'
)
insert into public.patient_profile_versions (
  id,
  patient_profile_id,
  version_number,
  state,
  schema_version,
  document,
  content_hash,
  change_summary,
  source_reference,
  source_revision,
  created_at,
  updated_at
)
select
  '24ae934e-6425-4b5c-a4d2-da9cde9590e3',
  profile.id,
  1,
  'draft',
  1,
  document,
  encode(sha256(convert_to(document::text, 'UTF8')), 'hex'),
  'Initial clinically informed import from the EPR Unified prototype; review required before publication.',
  'https://github.com/DNMSW/epr-unified',
  '03c7f12',
  '2026-08-30T00:00:00.000Z',
  '2026-08-30T00:00:00.000Z'
from content
cross join profile
on conflict (patient_profile_id, version_number) do nothing;

do $verify_version_adebayo_omolade$
declare
  expected_hash text;
  stored_hash text;
  stored_document_hash text;
begin
  select encode(
    sha256(convert_to($patient_document_adebayo_omolade$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Adebayo"
    ],
    "familyName": "Omolade",
    "dateOfBirth": "2006-03-15",
    "sexAtBirth": {
      "status": "known",
      "value": "male"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-63820",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "known",
      "value": {
        "display": "Black British, with family roots in Nigeria"
      }
    },
    "faithOrBelief": {
      "status": "known",
      "value": {
        "display": "Christian"
      }
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "proficiency": "fluent",
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [
      {
        "id": "plain-language",
        "summary": "Use plain language and avoid unexplained medical terminology.",
        "details": "Allow time to process information and check understanding without rushing."
      }
    ],
    "accessibilityNeeds": [
      {
        "id": "learning-disability-support",
        "summary": "Requires reasonable adjustments for a mild to moderate learning disability.",
        "details": "May become anxious or overwhelmed by complex written information and has a learning disability healthcare passport."
      }
    ]
  },
  "contact": {
    "address": {
      "lines": [
        "14 Ashton View"
      ],
      "city": "Tameside",
      "postalCode": "AS1 4NN",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "folake-omolade",
      "name": "Folake Omolade",
      "relationship": {
        "display": "Sister"
      },
      "roles": [
        "next_of_kin",
        "carer"
      ],
      "notes": "Main source of emotional and practical support, including help with appointments, forms and written information."
    }
  ],
  "background": [
    {
      "id": "living-with-sister",
      "category": "living_arrangements",
      "summary": "Lives with his older sister Folake.",
      "sensitivity": "standard"
    },
    {
      "id": "charity-shop-work",
      "category": "occupation",
      "summary": "Works part-time in a charity shop with support and values the structure and independence.",
      "sensitivity": "standard"
    },
    {
      "id": "prayer-when-worried",
      "category": "cultural",
      "summary": "Finds quiet prayer comforting when worried and prefers this to be approached sensitively.",
      "sensitivity": "standard"
    }
  ],
  "problems": [
    {
      "id": "type-2-diabetes",
      "problem": {
        "display": "Type 2 diabetes mellitus"
      },
      "clinicalStatus": "active",
      "details": "Diagnosed five months before the source scenario."
    },
    {
      "id": "learning-disability",
      "problem": {
        "display": "Learning disability"
      },
      "clinicalStatus": "active",
      "details": "Described as mild to moderate in the source material."
    }
  ],
  "allergies": [],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "A young adult with type 2 diabetes and a learning disability who values independence and benefits from accessible communication.",
    "lifeStage": "young_person",
    "careSettings": [
      "primary_care",
      "community"
    ],
    "specialties": [
      "diabetes",
      "learning_disability"
    ],
    "tags": [
      "accessibility",
      "carer_relationship",
      "cultural_context",
      "long_term_condition"
    ]
  }
}
$patient_document_adebayo_omolade$::jsonb::text, 'UTF8')),
    'hex'
  ) into expected_hash;

  select
    content_hash,
    encode(sha256(convert_to(document::text, 'UTF8')), 'hex')
  into stored_hash, stored_document_hash
  from public.patient_profile_versions version
  join public.patient_profiles profile
    on profile.id = version.patient_profile_id
  where profile.scope = 'system'
    and profile.slug = 'adebayo-omolade'
    and version_number = 1
    and version.state = 'draft'
    and version.schema_version = 1;

  if stored_hash is null or
     stored_hash <> expected_hash or
     stored_document_hash <> expected_hash then
    raise exception 'production_patient_profile_version_drift:adebayo-omolade';
  end if;
end;
$verify_version_adebayo_omolade$;

insert into public.patient_profiles (
  id, scope, slug, status, created_at, updated_at
) values (
  '367c5198-6a4f-4a06-8652-502db44062cc', 'system', 'amina-warsame', 'active', '2026-08-30T00:00:00.000Z', '2026-08-30T00:00:00.000Z'
) on conflict (slug) where scope = 'system' do nothing;

do $verify_profile_amina_warsame$
begin
  if not exists (
    select 1 from public.patient_profiles
    where scope = 'system'
      and slug = 'amina-warsame'
      and organisation_id is null
      and user_id is null
  ) then
    raise exception 'production_patient_profile_drift:amina-warsame';
  end if;
end;
$verify_profile_amina_warsame$;

with content as (
  select $patient_document_amina_warsame$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Amina"
    ],
    "familyName": "Warsame",
    "dateOfBirth": "1998-05-11",
    "sexAtBirth": {
      "status": "known",
      "value": "female"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-15238",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "known",
      "value": {
        "display": "Black African, Somali heritage"
      }
    },
    "faithOrBelief": {
      "status": "known",
      "value": {
        "display": "Muslim"
      }
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "proficiency": "fluent",
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [],
    "accessibilityNeeds": []
  },
  "contact": {
    "address": {
      "lines": [
        "12 Beresford Road"
      ],
      "city": "Manchester",
      "postalCode": "M16 8NG",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "yusuf-warsame",
      "name": "Yusuf Warsame",
      "relationship": {
        "display": "Husband"
      },
      "roles": [
        "next_of_kin"
      ],
      "notes": "Amina describes strong support from her husband and wider family."
    }
  ],
  "background": [
    {
      "id": "pharmacy-assistant",
      "category": "occupation",
      "summary": "Works part-time as a pharmacy dispensing assistant.",
      "sensitivity": "standard"
    },
    {
      "id": "family-support",
      "category": "family",
      "summary": "Has strong support from her husband and mother.",
      "sensitivity": "standard"
    },
    {
      "id": "muslim-practice",
      "category": "cultural",
      "summary": "Practising Muslim; requests halal food and welcomes family involvement in care planning.",
      "sensitivity": "standard"
    },
    {
      "id": "non-smoker",
      "category": "lifestyle",
      "summary": "Does not smoke.",
      "sensitivity": "standard"
    }
  ],
  "problems": [],
  "allergies": [],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "An adult with strong family support and Somali Muslim heritage, authored for maternity and postnatal learning experiences.",
    "lifeStage": "adult",
    "careSettings": [
      "maternity",
      "postnatal"
    ],
    "specialties": [
      "maternity"
    ],
    "tags": [
      "carer_relationship",
      "cultural_context",
      "newborn_relationship"
    ]
  }
}
$patient_document_amina_warsame$::jsonb as document
), profile as (
  select id
  from public.patient_profiles
  where scope = 'system'
    and slug = 'amina-warsame'
)
insert into public.patient_profile_versions (
  id,
  patient_profile_id,
  version_number,
  state,
  schema_version,
  document,
  content_hash,
  change_summary,
  source_reference,
  source_revision,
  created_at,
  updated_at
)
select
  'a2681834-dd66-4930-bebb-f24d682f742d',
  profile.id,
  1,
  'draft',
  1,
  document,
  encode(sha256(convert_to(document::text, 'UTF8')), 'hex'),
  'Initial clinically informed import from the EPR Unified prototype; review required before publication.',
  'https://github.com/DNMSW/epr-unified',
  '03c7f12',
  '2026-08-30T00:00:00.000Z',
  '2026-08-30T00:00:00.000Z'
from content
cross join profile
on conflict (patient_profile_id, version_number) do nothing;

do $verify_version_amina_warsame$
declare
  expected_hash text;
  stored_hash text;
  stored_document_hash text;
begin
  select encode(
    sha256(convert_to($patient_document_amina_warsame$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Amina"
    ],
    "familyName": "Warsame",
    "dateOfBirth": "1998-05-11",
    "sexAtBirth": {
      "status": "known",
      "value": "female"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-15238",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "known",
      "value": {
        "display": "Black African, Somali heritage"
      }
    },
    "faithOrBelief": {
      "status": "known",
      "value": {
        "display": "Muslim"
      }
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "proficiency": "fluent",
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [],
    "accessibilityNeeds": []
  },
  "contact": {
    "address": {
      "lines": [
        "12 Beresford Road"
      ],
      "city": "Manchester",
      "postalCode": "M16 8NG",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "yusuf-warsame",
      "name": "Yusuf Warsame",
      "relationship": {
        "display": "Husband"
      },
      "roles": [
        "next_of_kin"
      ],
      "notes": "Amina describes strong support from her husband and wider family."
    }
  ],
  "background": [
    {
      "id": "pharmacy-assistant",
      "category": "occupation",
      "summary": "Works part-time as a pharmacy dispensing assistant.",
      "sensitivity": "standard"
    },
    {
      "id": "family-support",
      "category": "family",
      "summary": "Has strong support from her husband and mother.",
      "sensitivity": "standard"
    },
    {
      "id": "muslim-practice",
      "category": "cultural",
      "summary": "Practising Muslim; requests halal food and welcomes family involvement in care planning.",
      "sensitivity": "standard"
    },
    {
      "id": "non-smoker",
      "category": "lifestyle",
      "summary": "Does not smoke.",
      "sensitivity": "standard"
    }
  ],
  "problems": [],
  "allergies": [],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "An adult with strong family support and Somali Muslim heritage, authored for maternity and postnatal learning experiences.",
    "lifeStage": "adult",
    "careSettings": [
      "maternity",
      "postnatal"
    ],
    "specialties": [
      "maternity"
    ],
    "tags": [
      "carer_relationship",
      "cultural_context",
      "newborn_relationship"
    ]
  }
}
$patient_document_amina_warsame$::jsonb::text, 'UTF8')),
    'hex'
  ) into expected_hash;

  select
    content_hash,
    encode(sha256(convert_to(document::text, 'UTF8')), 'hex')
  into stored_hash, stored_document_hash
  from public.patient_profile_versions version
  join public.patient_profiles profile
    on profile.id = version.patient_profile_id
  where profile.scope = 'system'
    and profile.slug = 'amina-warsame'
    and version_number = 1
    and version.state = 'draft'
    and version.schema_version = 1;

  if stored_hash is null or
     stored_hash <> expected_hash or
     stored_document_hash <> expected_hash then
    raise exception 'production_patient_profile_version_drift:amina-warsame';
  end if;
end;
$verify_version_amina_warsame$;

insert into public.patient_profiles (
  id, scope, slug, status, created_at, updated_at
) values (
  '2ebc8fdd-9ab8-4b2e-b314-ae895f58d23d', 'system', 'emma-barlow', 'active', '2026-08-30T00:00:00.000Z', '2026-08-30T00:00:00.000Z'
) on conflict (slug) where scope = 'system' do nothing;

do $verify_profile_emma_barlow$
begin
  if not exists (
    select 1 from public.patient_profiles
    where scope = 'system'
      and slug = 'emma-barlow'
      and organisation_id is null
      and user_id is null
  ) then
    raise exception 'production_patient_profile_drift:emma-barlow';
  end if;
end;
$verify_profile_emma_barlow$;

with content as (
  select $patient_document_emma_barlow$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Emma"
    ],
    "familyName": "Barlow",
    "dateOfBirth": "2016-02-15",
    "sexAtBirth": {
      "status": "known",
      "value": "female"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-52847",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "unknown"
    },
    "faithOrBelief": {
      "status": "unknown"
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [],
    "accessibilityNeeds": []
  },
  "contact": {
    "address": {
      "lines": [
        "7 Rowan Close"
      ],
      "city": "Manchester",
      "postalCode": "M20 3DT",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "nadine-barlow",
      "name": "Nadine Barlow",
      "relationship": {
        "display": "Mother"
      },
      "roles": [
        "parent",
        "guardian",
        "carer",
        "next_of_kin"
      ],
      "notes": "Emma's sole carer; her father has not been involved since infancy."
    }
  ],
  "background": [
    {
      "id": "single-parent-home",
      "category": "living_arrangements",
      "summary": "Lives with her mother, who is her sole carer.",
      "sensitivity": "standard"
    }
  ],
  "problems": [
    {
      "id": "childhood-cancer",
      "problem": {
        "display": "Childhood cancer"
      },
      "clinicalStatus": "active",
      "details": "The source profile deliberately leaves the cancer type to the later clinical record."
    }
  ],
  "allergies": [],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "A child living with cancer whose mother is her sole carer and whose care requires child- and family-centred communication.",
    "lifeStage": "child",
    "careSettings": [
      "paediatric_community",
      "home"
    ],
    "specialties": [
      "childrens_nursing",
      "oncology",
      "palliative_care"
    ],
    "tags": [
      "carer_relationship",
      "long_term_condition"
    ]
  }
}
$patient_document_emma_barlow$::jsonb as document
), profile as (
  select id
  from public.patient_profiles
  where scope = 'system'
    and slug = 'emma-barlow'
)
insert into public.patient_profile_versions (
  id,
  patient_profile_id,
  version_number,
  state,
  schema_version,
  document,
  content_hash,
  change_summary,
  source_reference,
  source_revision,
  created_at,
  updated_at
)
select
  '25928245-5cc1-463d-a7d6-8a4ad7cfb394',
  profile.id,
  1,
  'draft',
  1,
  document,
  encode(sha256(convert_to(document::text, 'UTF8')), 'hex'),
  'Initial clinically informed import from the EPR Unified prototype; review required before publication.',
  'https://github.com/DNMSW/epr-unified',
  '03c7f12',
  '2026-08-30T00:00:00.000Z',
  '2026-08-30T00:00:00.000Z'
from content
cross join profile
on conflict (patient_profile_id, version_number) do nothing;

do $verify_version_emma_barlow$
declare
  expected_hash text;
  stored_hash text;
  stored_document_hash text;
begin
  select encode(
    sha256(convert_to($patient_document_emma_barlow$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Emma"
    ],
    "familyName": "Barlow",
    "dateOfBirth": "2016-02-15",
    "sexAtBirth": {
      "status": "known",
      "value": "female"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-52847",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "unknown"
    },
    "faithOrBelief": {
      "status": "unknown"
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [],
    "accessibilityNeeds": []
  },
  "contact": {
    "address": {
      "lines": [
        "7 Rowan Close"
      ],
      "city": "Manchester",
      "postalCode": "M20 3DT",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "nadine-barlow",
      "name": "Nadine Barlow",
      "relationship": {
        "display": "Mother"
      },
      "roles": [
        "parent",
        "guardian",
        "carer",
        "next_of_kin"
      ],
      "notes": "Emma's sole carer; her father has not been involved since infancy."
    }
  ],
  "background": [
    {
      "id": "single-parent-home",
      "category": "living_arrangements",
      "summary": "Lives with her mother, who is her sole carer.",
      "sensitivity": "standard"
    }
  ],
  "problems": [
    {
      "id": "childhood-cancer",
      "problem": {
        "display": "Childhood cancer"
      },
      "clinicalStatus": "active",
      "details": "The source profile deliberately leaves the cancer type to the later clinical record."
    }
  ],
  "allergies": [],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "A child living with cancer whose mother is her sole carer and whose care requires child- and family-centred communication.",
    "lifeStage": "child",
    "careSettings": [
      "paediatric_community",
      "home"
    ],
    "specialties": [
      "childrens_nursing",
      "oncology",
      "palliative_care"
    ],
    "tags": [
      "carer_relationship",
      "long_term_condition"
    ]
  }
}
$patient_document_emma_barlow$::jsonb::text, 'UTF8')),
    'hex'
  ) into expected_hash;

  select
    content_hash,
    encode(sha256(convert_to(document::text, 'UTF8')), 'hex')
  into stored_hash, stored_document_hash
  from public.patient_profile_versions version
  join public.patient_profiles profile
    on profile.id = version.patient_profile_id
  where profile.scope = 'system'
    and profile.slug = 'emma-barlow'
    and version_number = 1
    and version.state = 'draft'
    and version.schema_version = 1;

  if stored_hash is null or
     stored_hash <> expected_hash or
     stored_document_hash <> expected_hash then
    raise exception 'production_patient_profile_version_drift:emma-barlow';
  end if;
end;
$verify_version_emma_barlow$;

insert into public.patient_profiles (
  id, scope, slug, status, created_at, updated_at
) values (
  '37ea1fbc-d47c-4b75-b918-19af6184bb3b', 'system', 'esther-jenkins', 'active', '2026-08-30T00:00:00.000Z', '2026-08-30T00:00:00.000Z'
) on conflict (slug) where scope = 'system' do nothing;

do $verify_profile_esther_jenkins$
begin
  if not exists (
    select 1 from public.patient_profiles
    where scope = 'system'
      and slug = 'esther-jenkins'
      and organisation_id is null
      and user_id is null
  ) then
    raise exception 'production_patient_profile_drift:esther-jenkins';
  end if;
end;
$verify_profile_esther_jenkins$;

with content as (
  select $patient_document_esther_jenkins$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Esther"
    ],
    "familyName": "Jenkins",
    "dateOfBirth": "1951-09-19",
    "pronouns": {
      "status": "known",
      "value": [
        "she",
        "her"
      ]
    },
    "sexAtBirth": {
      "status": "known",
      "value": "female"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-37194",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "known",
      "value": {
        "display": "White British"
      }
    },
    "faithOrBelief": {
      "status": "unknown"
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [],
    "accessibilityNeeds": []
  },
  "contact": {
    "address": {
      "lines": [
        "34 Beech Grove"
      ],
      "city": "Manchester",
      "postalCode": "M11 2QP",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "tasha-jenkins",
      "name": "Tasha Jenkins",
      "relationship": {
        "display": "Daughter"
      },
      "roles": [
        "next_of_kin",
        "carer"
      ],
      "notes": "Lives with Esther and is her main source of support."
    }
  ],
  "background": [
    {
      "id": "retired-cleaner",
      "category": "occupation",
      "summary": "Retired cleaner.",
      "sensitivity": "standard"
    },
    {
      "id": "living-with-daughter",
      "category": "living_arrangements",
      "summary": "Lives with her daughter Tasha in a two-bedroom terraced house.",
      "sensitivity": "standard"
    },
    {
      "id": "widowed",
      "category": "adverse_life_event",
      "summary": "Widowed and experienced a depressive episode after her husband's death.",
      "details": "Previously took antidepressants for two years.",
      "sensitivity": "standard"
    }
  ],
  "problems": [
    {
      "id": "hypertension",
      "problem": {
        "display": "Hypertension"
      },
      "clinicalStatus": "active"
    },
    {
      "id": "atrial-fibrillation",
      "problem": {
        "display": "Atrial fibrillation"
      },
      "clinicalStatus": "active"
    },
    {
      "id": "past-depressive-episode",
      "problem": {
        "display": "Depressive episode"
      },
      "clinicalStatus": "resolved",
      "details": "Occurred after bereavement and was treated with antidepressants for two years."
    }
  ],
  "allergies": [
    {
      "id": "erythromycin",
      "substance": {
        "display": "Erythromycin"
      },
      "clinicalStatus": "active",
      "verificationStatus": "unconfirmed",
      "reactions": [
        "Diarrhoea",
        "Stomach pains"
      ],
      "details": "Patient-reported reaction in the source profile."
    }
  ],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "An older adult with hypertension and atrial fibrillation, living with and supported by her daughter, suitable for acute stroke and interprofessional learning.",
    "lifeStage": "older_adult",
    "careSettings": [
      "acute_inpatient"
    ],
    "specialties": [
      "stroke",
      "interprofessional"
    ],
    "tags": [
      "carer_relationship",
      "long_term_condition"
    ]
  }
}
$patient_document_esther_jenkins$::jsonb as document
), profile as (
  select id
  from public.patient_profiles
  where scope = 'system'
    and slug = 'esther-jenkins'
)
insert into public.patient_profile_versions (
  id,
  patient_profile_id,
  version_number,
  state,
  schema_version,
  document,
  content_hash,
  change_summary,
  source_reference,
  source_revision,
  created_at,
  updated_at
)
select
  '016a3ade-5634-4773-9c08-5c7984af3cec',
  profile.id,
  1,
  'draft',
  1,
  document,
  encode(sha256(convert_to(document::text, 'UTF8')), 'hex'),
  'Initial clinically informed import from the EPR Unified prototype; review required before publication.',
  'https://github.com/DNMSW/epr-unified',
  '03c7f12',
  '2026-08-30T00:00:00.000Z',
  '2026-08-30T00:00:00.000Z'
from content
cross join profile
on conflict (patient_profile_id, version_number) do nothing;

do $verify_version_esther_jenkins$
declare
  expected_hash text;
  stored_hash text;
  stored_document_hash text;
begin
  select encode(
    sha256(convert_to($patient_document_esther_jenkins$
{
  "schemaVersion": 1,
  "synthetic": true,
  "identity": {
    "givenNames": [
      "Esther"
    ],
    "familyName": "Jenkins",
    "dateOfBirth": "1951-09-19",
    "pronouns": {
      "status": "known",
      "value": [
        "she",
        "her"
      ]
    },
    "sexAtBirth": {
      "status": "known",
      "value": "female"
    }
  },
  "identifiers": [
    {
      "id": "hektor-patient-number",
      "kind": "local_patient_number",
      "value": "SIM-HKT-37194",
      "display": "Hektor patient number",
      "issuer": "Hektor",
      "synthetic": true
    }
  ],
  "demographics": {
    "ethnicity": {
      "status": "known",
      "value": {
        "display": "White British"
      }
    },
    "faithOrBelief": {
      "status": "unknown"
    }
  },
  "communication": {
    "languages": [
      {
        "id": "english",
        "language": {
          "display": "English"
        },
        "interpreterRequired": {
          "status": "known",
          "value": false
        }
      }
    ],
    "preferredLanguageId": "english",
    "preferences": [],
    "accessibilityNeeds": []
  },
  "contact": {
    "address": {
      "lines": [
        "34 Beech Grove"
      ],
      "city": "Manchester",
      "postalCode": "M11 2QP",
      "country": "United Kingdom",
      "synthetic": true
    }
  },
  "relationships": [
    {
      "id": "tasha-jenkins",
      "name": "Tasha Jenkins",
      "relationship": {
        "display": "Daughter"
      },
      "roles": [
        "next_of_kin",
        "carer"
      ],
      "notes": "Lives with Esther and is her main source of support."
    }
  ],
  "background": [
    {
      "id": "retired-cleaner",
      "category": "occupation",
      "summary": "Retired cleaner.",
      "sensitivity": "standard"
    },
    {
      "id": "living-with-daughter",
      "category": "living_arrangements",
      "summary": "Lives with her daughter Tasha in a two-bedroom terraced house.",
      "sensitivity": "standard"
    },
    {
      "id": "widowed",
      "category": "adverse_life_event",
      "summary": "Widowed and experienced a depressive episode after her husband's death.",
      "details": "Previously took antidepressants for two years.",
      "sensitivity": "standard"
    }
  ],
  "problems": [
    {
      "id": "hypertension",
      "problem": {
        "display": "Hypertension"
      },
      "clinicalStatus": "active"
    },
    {
      "id": "atrial-fibrillation",
      "problem": {
        "display": "Atrial fibrillation"
      },
      "clinicalStatus": "active"
    },
    {
      "id": "past-depressive-episode",
      "problem": {
        "display": "Depressive episode"
      },
      "clinicalStatus": "resolved",
      "details": "Occurred after bereavement and was treated with antidepressants for two years."
    }
  ],
  "allergies": [
    {
      "id": "erythromycin",
      "substance": {
        "display": "Erythromycin"
      },
      "clinicalStatus": "active",
      "verificationStatus": "unconfirmed",
      "reactions": [
        "Diarrhoea",
        "Stomach pains"
      ],
      "details": "Patient-reported reaction in the source profile."
    }
  ],
  "baselineMedications": [],
  "catalogue": {
    "synopsis": "An older adult with hypertension and atrial fibrillation, living with and supported by her daughter, suitable for acute stroke and interprofessional learning.",
    "lifeStage": "older_adult",
    "careSettings": [
      "acute_inpatient"
    ],
    "specialties": [
      "stroke",
      "interprofessional"
    ],
    "tags": [
      "carer_relationship",
      "long_term_condition"
    ]
  }
}
$patient_document_esther_jenkins$::jsonb::text, 'UTF8')),
    'hex'
  ) into expected_hash;

  select
    content_hash,
    encode(sha256(convert_to(document::text, 'UTF8')), 'hex')
  into stored_hash, stored_document_hash
  from public.patient_profile_versions version
  join public.patient_profiles profile
    on profile.id = version.patient_profile_id
  where profile.scope = 'system'
    and profile.slug = 'esther-jenkins'
    and version_number = 1
    and version.state = 'draft'
    and version.schema_version = 1;

  if stored_hash is null or
     stored_hash <> expected_hash or
     stored_document_hash <> expected_hash then
    raise exception 'production_patient_profile_version_drift:esther-jenkins';
  end if;
end;
$verify_version_esther_jenkins$;

commit;
